In [1]:
import pandas as pd
import numpy as np

In [6]:
codes, uniques = pd.factorize(['b', 'b', 'a', 'c', 'b'])

In [7]:
codes

array([0, 0, 1, 2, 0], dtype=int64)

In [8]:
uniques

array(['b', 'a', 'c'], dtype=object)

In [9]:
codes, uniques = pd.factorize(['b', 'b', 'a', 'c', 'b'], sort=True)

In [10]:
codes

array([1, 1, 0, 2, 1], dtype=int64)

In [11]:
uniques

array(['a', 'b', 'c'], dtype=object)

In [12]:
codes, uniques = pd.factorize(['b', None, 'a', 'c', 'b'])

In [13]:
codes

array([ 0, -1,  1,  2,  0], dtype=int64)

In [14]:
uniques

array(['b', 'a', 'c'], dtype=object)

In [15]:
cat = pd.Categorical(['a', 'a', 'c'], categories=['a', 'b', 'c'])

In [16]:
codes, uniques = pd.factorize(cat)

In [17]:
codes

array([0, 0, 1], dtype=int64)

In [18]:
uniques

['a', 'c']
Categories (3, object): ['a', 'b', 'c']

In [19]:
cat = pd.Series(['a', 'a', 'c'])

In [20]:
cat

0    a
1    a
2    c
dtype: object

In [21]:
codes, uniques = pd.factorize(cat)

In [22]:
codes

array([0, 0, 1], dtype=int64)

In [23]:
uniques

Index(['a', 'c'], dtype='object')

In [24]:
values = np.array([1, 2, 1, np.nan])

In [25]:
codes, uniques = pd.factorize(values)

In [26]:
codes

array([ 0,  1,  0, -1], dtype=int64)

In [27]:
uniques

array([1., 2.])

In [31]:
values = np.array([1, 2, 1, np.nan])

In [28]:
codes, uniques = pd.factorize(values, na_sentinel=None)

In [29]:
codes

array([0, 1, 0, 2], dtype=int64)

In [30]:
uniques

array([ 1.,  2., nan])